### ISSUE TITLE
Subdomain example shutdown if port is 80.

### ISSUE THREAD

**Issue by timakin** [iris-contrib/examples#1]
https://github.com/iris-contrib/examples/blob/master/subdomains_simple/main.go#L32

When I build subdomains_simple example, 
its process immediately shutdown.
And I could fix it if I changed the receiver port other than 80.
Is it a bug ? If not, could you tell me the solution?

**Comment by kataras** [comment]
Yes it's fasthttp's bug which I understand right now, I 'm fixing this look again at 5 minutes please, thanks for the issue!

**Comment by kataras** [comment]
@timakin  The issue has been fixed, thanks for reporting that!!

Upgrade the Iris and test again!
```
go get -u github.com/kataras/iris
```

**Comment by timakin** [comment]
@kataras Thank you for your updates!
I noticed Iris properly returns `ErrServerPortAlreadyUsed ` error,
but it should show the log thet it forcibly shutdown the process.
I couldn`t see it at first.

Maybe it is related to all of Iris Error Handling.
Is there any place to discuss it?

**Comment by kataras** [comment]
@timakin  yes you can always open an issue and recommend things [here](https://github.com/kataras/iris/issues/) https://github.com/kataras/iris/issues/ You're right I have to panic on this state for port already used

**Comment by timakin** [comment]
@kataras Thank you for your kindness.
I'll create an issue to consider how to handle errors 😆
