### ISSUE TITLE
file_upload_simple not working with go 1.8?

### ISSUE THREAD

**Issue by flockonus** [iris-contrib/examples#14]
Just installed iris.v6 today and , downloaded this repo and tried to run 

https://github.com/iris-contrib/examples/tree/master/file_upload_simple

```
cd file_upload_simple
go run main.go
```

The server executes and http://127.0.0.1:8080/upload is available, but after the upload get the message: `Error while uploading: open ./uploads/Screen Shot 2017-02-21 at 4.52.14 PM.png: no such file or directory`

I get no logs in the console either, either of what worked or didn't (which maybe is a bug on iris?)

If i `mkdir uploads` then it seems to work

**Comment by kataras** [comment]
Yes, github skipped `./uploads` folder because it's empty. I'll add a `.keep` file.

> I get no logs in the console either, either of what worked or didn't (which maybe is a bug on iris?)

It has nothing to do with Iris, you can do upload functionality with a lot of different ways, these examples are just for getting started with go and Iris, you shouldn't copy-paste code for production use lol
