### ISSUE TITLE
More examples with partials in templates

### ISSUE THREAD

**Issue by dangerousHobo** [iris-contrib/examples#2]
Could an example be added to show how to use partials in the templates with Render? I've read through this section in the book and then made the following example but I'm still missing something as my partials are not rendered. So more details would be helpful.

I have the following:

```
$ tree
.
├── templates
│   ├── footer-layout.html
│   ├── header-layout.html
│   ├── layout.html
│   └── mypage.html
└── web.go
```

web.go
```go
package main

import (
    "github.com/kataras/iris"
)

type mypage struct {
    Title   string
    Message string
}

func main() {
    iris.Config().Render.Directory = "templates"
    iris.Config().Render.Layout = "layout"
    iris.Config().Render.Gzip = true

    iris.Get("/", func(ctx *iris.Context) {
        ctx.Render("mypage", mypage{"My Page title", "Hello world!"})
    })

    println("Server is running at :8080")
    iris.Listen(":8080")
}
```

footer-layout.html
```html
{{ define "footer-layout" }}
<h1>FOOTER</h1>
{{ end }}
```

header-layout.html
```html
{{ define "header-layout" }}
<h1>HEADER</h1>
{{ end }}
```

layout.html
```html
<!-- templates/layout.html -->
<html>
  <head>
    <title>My Layout</title>
  </head>
  <body>
    <!-- render the partial template called `header-$current_template` here -->
    {{ partial "header" }}
    <!-- Render the current template here -->
    {{ yield }}
    <!-- render the partial template called `footer-$current_template` here -->
    {{ partial "footer" }}
  </body>
</html>
```

mypage.html
```html
<h1>TEST</h1>
<h2>
    {{.Title}}
    <pre>{{.Message}}</pre>
</h2>
```

I figure it's something simple I'm missing. Can someone help me get this working?

Thanks.

**Comment by dangerousHobo** [comment]
Okay, I was able to figure my issue out.
I was expecting current template to be the template that the partial was defined in and not what was being rendered.

So by making the following change I solved my issue:

footer-layout.html
```
{{ define "footer-mypage" }}
<h1>FOOTER</h1>
{{ end }}
```

header-layout.html
```
{{ define "header-mypage" }}
<h1>HEADER</h1>
{{ end }}
```

**Comment by kataras** [comment]
Nice, now it's time to add this as an example if you want, make a pull request for his on the iris-contrib/examples to help more people with the same issue , thanks you!

**Comment by dangerousHobo** [comment]
Will do. I plan on writing several small examples to help myself learn. Once done I'll submit them as a pull-request.

**Comment by kataras** [comment]
Very good, happy coding!!
