### ISSUE TITLE
get with params

### ISSUE THREAD

**Issue by ithemant09** [iris-contrib/examples#26]
Hi @kataras 
I am very new to scripting programming.
Can you help me with below doubt.

I have GET request with parameter say "/pass?result=33" , based on result value my response will differ. How I can achieve this using iris framework.

app.Get("/pass?{result:int}", func(ctx iris.Context) {
	    result, _ := ctx.Params().GetInt("result")
		if result > 33 {
ctx.WriteString("Pass")
} else {
ctx.WriteString("Fail")
}
})

It is not working

**Comment by kataras** [comment]
**`{result:int}` is a path parameter**, i.e `app.Get("/pass/{result:int{")` (without the ? of course), and request at `http://localhost:8080/pass/42`, the `42` here is the `ctx.Params().GetInt("result")`. But you are speaking about **url query parameters**, you don't have to register the parameter, it can be anything and can be retrieve using the `ctx.URLParam` functions, look;

```go
app.Get("/pass", func(ctx iris.Context){
    result,_ := ctx.URLParamInt("result")
    // if result > 33 ...
})

```

**Comment by kataras** [comment]
**`{result:int}` is a path parameter**, i.e `app.Get("/pass/{result:int}", handler)` (without the ? of course), and request at `http://localhost:8080/pass/42`, the `42` here is the `ctx.Params().GetInt("result")`. But you are speaking about **url query parameters**, you don't have to register the parameter, it can be anything and can be retrieve using the `ctx.URLParam` functions, look;

```go
app.Get("/pass", func(ctx iris.Context){
    result,_ := ctx.URLParamInt("result")
    // if result > 33 ...
})

```

**Comment by ithemant09** [comment]
Thanks @kataras , It's working.
