### ISSUE TITLE
how to read data from client like JMeter

### ISSUE THREAD

**Issue by XinhongWu** [iris-contrib/examples#27]
I want to do load-test using tool JMeter.
The test-steps include:
1) client sends a message (eg. a single string or key-value object) to a server
2) Then the server receives the message and return back the string value  to client

At present, I haven't found a func to help me finish my work.

I try to do coding as follows:

package main

import (
	"fmt"
	"github.com/kataras/iris"
	"github.com/kataras/iris/websocket"
)

func main()  {
	app := iris.New()

	ws := websocket.New(websocket.Config{
		ReadBufferSize:  1024,
		WriteBufferSize: 1024,
	})

	ws.OnConnection(handleConnection)

	app.Get("/echo", ws.Handler())

	app.Run(iris.Addr(":8080"))

}

func handleConnection(c websocket.Connection) {
	fmt.Println("read start...")
	recvString := c.GetValueString("name")
	fmt.Println("receive string is ",recvString)
	c.EmitMessage([]byte(recvString))
}

I send a key-value  {"name":"Clark"}
However I can get the right response
Can you help me， thanks very much!

**Comment by kataras** [comment]
The server-side is correct, if you have the "name" filled, but where's your client-side source code?

**Comment by XinhongWu** [comment]
@kataras thanks for your reply. 
The client is JMeter, and the message is sent in the general way.
If the server code is using the origin go websocket, the message from JMeter can be received.
The server code is as below:
`package main

import (
	"golang.org/x/net/websocket"
	"fmt"
	"log"
	"net/http"
)

func webHandler(ws *websocket.Conn) {
	msg := make([]byte, 512)
	n, err := ws.Read(msg)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Receive: %s\n", msg[:n])

	send_msg := "[" + string(msg[:n]) + "]"
	m, err := ws.Write([]byte(send_msg))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Send: %s\n", msg[:m])
}

func main() {
	http.HandleFunc("/echo",
	func (w http.ResponseWriter, req *http.Request) {
        s := websocket.Server{Handler: websocket.Handler(webHandler)}
        s.ServeHTTP(w, req)
    });

	err := http.ListenAndServe(":8080", nil)

	if err != nil {
		panic("ListenAndServe: " + err.Error())
	}
}`

Is Iris having the similar function like ws.Read() ?
If so then I can get message under Iris framework

**Comment by kataras** [comment]
There is an example for the `golang.org/x/net/websocket` as client-side talks to an Iris websocket server; https://github.com/iris-contrib/examples/blob/master/websocket/custom-go-client/main.go#L47

**Comment by XinhongWu** [comment]
@kataras Thanks very much
I have solved the problem using the golang.org/x/net/websocket as the server.
JMeter can recognize the websocket server using the origin go-websocket.
