### ISSUE TITLE
An PUT/POST issue in examples/api_handler_2/main.go

### ISSUE THREAD

**Issue by uicosp** [iris-contrib/examples#3]
Hi Kataras,
I think the PUT and POST  methods were used incorrectly in examples/api_handler_2/main.go.
Have a look at the discuss on stackoverflow http://stackoverflow.com/questions/630453/put-vs-post-in-rest.
Also, http://restcookbook.com/HTTP%20Methods/put-vs-post/

**Comment by kataras** [comment]
Hi uicosp, 
What's the problem? Put for create and Post for update, as inside the examples. Did you read the posted articles? :)

**Comment by kataras** [comment]
Hello uicosp, I already read a lot of books and articles before a decade or so,  if you think something should change create a pr!

**Comment by uicosp** [comment]
Actually , both PUT and POST can be used to create. The diff is that PUT need a explicit URI while POST doesn't.
e.g.

// Create a user with id=1
PUT /users/1 HTTP/1.1
Host: www.example.com/

// Create a user, and let the server side decide the user_id (usually returned by database)
POST /users HTTP/1.1
Host: www.example.com/

**Comment by kataras** [comment]
Correct, but the example is not to learn developers the web , with `PostBy` I want to show them that you can append the word `By` to receive parameters, this happens with all methods, not only post lawl

**Comment by uicosp** [comment]
yeah.
Iris is a awesome web framework, I like it very much. Since we found this issue, I think we can make it more correct to avoid misleading those who reading this example.
If you like, I can help you correct it and push a pr :)

**Comment by kataras** [comment]
'Joke' is coming...

> Iris is a awesome web framework, 

Yes but you didn't star it yet!!


Yes, I told twice, any help is welcome!

**Comment by uicosp** [comment]
Oh, I forgot to star it, haha. (Usually, I use "star" as bookmark to remember those good stuffs which I can find them later. I just found iris several days ago, and since it's so awesome that I can keep it in mind, so I forgot to star it.)
