### ISSUE TITLE
why static file can't be packaged

### ISSUE THREAD

**Issue by itgeniusshuai** [iris-contrib/examples#34]
I use your steps:
        // $ go get -u github.com/shuLhan/go-bindata/...
	// $ go-bindata ./templates/...
	// $ go build
	// $ ./embedding-templates-into-app
	// html files are not used, you can delete the folder and run the example.
	tmpl.Binary(Asset, AssetNames) // <-- IMPORTANT

my code is  :
![image](https://user-images.githubusercontent.com/18460477/41135013-f6fd030c-6b01-11e8-9207-cacbf634798d.png)
my dir structure is : 
![image](https://user-images.githubusercontent.com/18460477/41135029-15f69dcc-6b02-11e8-963e-4e17770107d6.png)
generated file is : 
![image](https://user-images.githubusercontent.com/18460477/41135050-3e8ddb24-6b02-11e8-859a-fee84ab534c9.png)

I can access normally when I don't build, anything wrong or my dir structure wrong?

**Comment by kataras** [comment]
You use `$ go-bindata ./templates/...` instead of `$ go-bindata ./web/views/...`

**Comment by kataras** [comment]
Yes, of course because `./templates/...` in the example is the folder which contains the `.html` templates, you must change it to `./web/views/...` because you use other target directory than the examples do.

**Comment by itgeniusshuai** [comment]
I see ,I add a param `-pkg web`,and remove `*.map` in js dir, it works well. if don't remove,the generated go file bindata.go will be very big,I can't compile by `go build`.  
With this function ,I can deploy conveniently
Thank you for your answer

**Comment by kataras** [comment]
I thank you!
