### ISSUE TITLE
Can we use mvc service in another service? 

### ISSUE THREAD

**Issue by zheeeng** [iris-contrib/examples#37]
At present we can only call service in controllers. Expect such a way to call a service cross services.

**Comment by jebzmos4** [comment]
That will be great to have. but @zheeeng how about a re-architecture or folder re-structure to avoid this?

**Comment by zheeeng** [comment]
Yes, I have done re-architecture my project. Expecting on such the ability are introduced. Maybe I should request a built-in service concept in MVC structure.

**Comment by kataras** [comment]
@zheeeng  you can use the `kataras/iris/hero` package that it bind services, and dynamic values exactly like Controller but in your handler functions!! Its example contains flow-screenshots as well for better understanding, check it: https://github.com/iris-contrib/examples/tree/master/hero/basic#2-services---static-dependencies

![](https://raw.githubusercontent.com/kataras/explore/master/iris/hero/hero-2-monokai.png)
