### ISSUE TITLE
"WithoutVersionChecker" is undefined!

### ISSUE THREAD

**Issue by mehranabi** [iris-contrib/examples#39]
Hello, Thanks for this amazing library,
I'm new to Go and Iris, I've installed examples (I've installed Iris too), but when I try to run the server by `go run main.go` in *overview* directory, I get this error: `.\main.go:77:57: undefined: iris.WithoutVersionChecker`

I've also tried to comment `iris.WithoutVersionChecker` in the code, the code will run after that but I get `404 not found` on all of request/routes...

**Comment by cci8go** [comment]
overview/main.go:77:57: undefined: iris.WithoutVersionChecker

**Comment by kataras** [comment]
The https://github.com/kataras/iris/tree/master/_examples contains the most updated examples, this is why I am so late to answer here guys. Although it's fixed  here too by: https://github.com/iris-contrib/examples/pull/45
