### ISSUE TITLE
If I post a data ,there is aways "Not Found". The post API is never triggerd

### ISSUE THREAD

**Issue by xubing** [iris-contrib/examples#7]
I use curl to simulate the post action, it return "Not Found",and it never step in PostBy() function.
`
curl -d "name=12" http://localhost:8080/users/ 

curl -d "name=12" http://localhost:8080/users/1/
 
`

**Comment by kataras** [comment]
Because you din't use the "POST" method? I 'm just saying...

**Comment by kataras** [comment]
You should try with `-f ` no with -`d` -d is for raw form data, -f is for form data which PostBy on the examples take with `u.FormValue` .

 Just checked with postman also, if you want url-encoded form data then use the `u.PostArgs().Peek("name")` . This is not an API's problem, the code is used inside handlers it's your own responsibility
