### ISSUE TITLE
Serve SPA files and /api route

### ISSUE THREAD

**Issue by mikepc** [iris-contrib/examples#9]
Hello there - I'm trying to configure iris to do a couple of things.

I want it to serve up static content for an angular SPA (in html5 mode) which means I will want to redirect all routes that don't start with /api to the static middleware, but for all actions below /api I will have custom handlers.

Code:
package main

import (
        "github.com/kataras/iris"
        //      "github.com/kataras/iris/utils"
        //      "strings"
)

func allVendorBrandLabel(c *iris.Context) {
        c.WriteString("Hello, api :)")

}
func main() {

```
    iris.Get("/api/all", allVendorBrandLabel)
    iris.StaticWeb("/", "./www", 2)
    iris.Listen(":8080")
```

}

This results in the root route failing with a 404, but the /api/ call returns nominally.

What do I need to accomplish this?

I also posted the question to StackOverflow to see how I could get it working:
http://stackoverflow.com/questions/38922585/how-to-serve-api-and-html5-spa-with-iris

**Comment by kataras** [comment]
Yes, because `iris.StaticWeb` will override the /api/all it will think it as `/api/all/index.html` because you're using the `StaticWeb`. You could use the `context.ServeFile` on a wildcard `/*path` route, and inside this handler do a `if path:= context.Param("path") ; path == "/api/all" { allVendorBrandLabel(context)} else { ctx.ServeFile(path) }` try this and tell me the results

**Comment by mikepc** [comment]
Thank you very much for your very helpful response.

`package main

import "github.com/kataras/iris"

func main() {
    admin := iris.Party("/admin", func(ctx *iris.Context){ ctx.Write("Middleware for all party's routes!") })
    {
        // add a silly middleware
        admin.UseFunc(func(c *iris.Context) {
            //your authentication logic here...
            println("from ", c.PathString())
            authorized := true
            if authorized {
                c.Next()
            } else {
                c.Text(401, c.PathString()+" is not authorized for you")
            }

        })
        admin.Get("/", func(c *iris.Context) {
            c.Write("from /admin/ or /admin if you pathcorrection on")
        })
        admin.Get("/dashboard", func(c *iris.Context) {
            c.Write("/admin/dashboard")
        })
        admin.Delete("/delete/:userId", func(c *iris.Context) {
            c.Write("admin/delete/%s", c.Param("userId"))
        })
    }


    beta := admin.Party("/beta")
    beta.Get("/hey", func(c *iris.Context) { c.Write("hey from /admin/beta/hey") })

    iris.Listen(":8080")
}`

That's the final code to get it to work.

It would be nice to have a more elegant way to approach this though, as the api portion of the app matures, it would be nice to handle it in a more similar way to other routes.

**Comment by kataras** [comment]
I just think it simpler, you could just use other `iris station and server` for static files and other for SPA, 

```go
statics := iris.New()
statics.StaticWeb("/","./www",2)
go statics.Listen(":9090")

iris.Get("/api/all",...)
```

**Comment by kataras** [comment]
I just think it simpler, you could just use other `iris station and server` for static files and other for SPA, 

```go
statics := iris.New()
statics.StaticWeb("/","./www",2)
go statics.Listen(":9090")

iris.Get("/api/all",...)
iris.Listen(":8080")
```

**Comment by kataras** [comment]
Please add this link to your question at stackoverflow, and star iris and this repository in order to be updated for all changes (I'm putting new examples every day almost)

**Comment by mikepc** [comment]
yeah I wanted to host the content in in a CDN or S3 bucket, it's just not possible. I need to serve the api and the content on a single port for business reasons.

**Comment by kataras** [comment]
I understand, but Static functions uses wildcard routes to catch all files, we can just use something like ` if path:= context.Param("path"); utils.DirectoryExists(path) { context.ServeFile(path) }else{ do something else }` I will think a way for SPA, it's good to have one func for these type of problems

**Comment by mikepc** [comment]
I don't know how badly the performance would be impacted, but how about defining a regex for the wildcard routes to let you say all routes except for api? I only suggest it since I'm assuming it's already using a regex to break out the path.

**Comment by mikepc** [comment]
At one point I set up a Party on /api, but the handler never executed (no error by the way, the server just returned a 200 empty response, So maybe the Party logic would be a good path to take, since fundamentally I think it makes sense to say "these requests go to these routes" for the "Party"

**Comment by kataras** [comment]
> but how about defining a regex for the wildcard routes to let you say all routes except for api? I only suggest it since I'm assuming it's already using a regex to break out the path.

If we used regex it will be  the slowest framework's router, regex are very slow on golang we will never use them, trust me. 

>  So maybe the Party logic would be a good path to take, since fundamentally I think it makes sense to say "these requests go to these routes" for the "Party" 

`iris.` is already a party of "/" so this is not the answer, we have big problem because static functions should use wildcard to catch all available files to serve, or we could just take the filenames and not use a wildcard but this will have a down-side when you add/remove files when iris is running, so this is not the answer, I will find a way soon don't worry

**Comment by mikepc** [comment]
You rock man, iris is the best Go web framework out there in my opinion, which is why when I came to this team at Nordstrom I used it for my first project. I have used it in the past for several microservices on other projects and it worked splendidly. Will keep checking back! Right now there's just one endpoint so I can get started.

**Comment by kataras** [comment]
Yes, also keep note that I will add support for custom 'child router' so only if you want you  will can use regex to your paths, it will no have perfomance panelaties if you don't use but if you use it then you will have, thanks for your nice words, I'm doing my best and all people helping helped me with bug reporting and ideas!

**Comment by SilentTiger** [comment]
I think this is really an important issue, because I've got the same problem.
![default](https://cloud.githubusercontent.com/assets/764862/18666826/69c57f84-7f60-11e6-8934-cb1e3f9ffd2b.PNG)

As  u see, at the line 33, when I set the static folder 'templates/static' to the root path, I got conflicts. And from line 41 to line 92, I have almost 50 different routes, so if I set them in if...else... that will be really ugly.

**Comment by kataras** [comment]
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	usersAPI := iris.None("/api/users/:userid", func(ctx *iris.Context) {
		ctx.Writef("user with id: %s", ctx.Param("userid"))
	})("api.users.id")

	iris.StaticWeb("/", "./www", usersAPI)

	iris.Listen("localhost:8080")
}
```

@mikepc Surprise :D 

Discussion: https://github.com/kataras/iris/issues/585

**Comment by kataras** [comment]
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	usersAPI := iris.None("/api/users/:userid", func(ctx *iris.Context) {
		ctx.Writef("user with id: %s", ctx.Param("userid"))
	})("api.users.id")

      // third parameter is optional, if not empty then these routes 
      // will have priority over the static handler when the request path is one of their route's path
      iris.StaticWeb("/", "./www", usersAPI)

	iris.Listen("localhost:8080")
}
```

@mikepc Surprise :D 

Discussion: https://github.com/kataras/iris/issues/585

**Comment by kataras** [comment]
```go
package main

import (
	"github.com/kataras/iris"
)

func main() {
	usersAPI := iris.None("/api/users/:userid", func(ctx *iris.Context) {
		ctx.Writef("user with id: %s", ctx.Param("userid"))
	})("api.users.id")

      // third parameter is optional, if not empty then these routes 
      // will have priority over the static handler when the request path is one of their route's path
      iris.StaticWeb("/", "./www", usersAPI)

      iris.Listen("localhost:8080")
}
```

@mikepc Surprise :D 

Discussion: https://github.com/kataras/iris/issues/585
